import { useState, useEffect, useCallback, useRef } from 'react'
import type { Algorithm, SimulationStep, SimulatorState, SimulatorActions } from '../types'
import { simulate } from '../logic/fifo/lru'
import { exportCSV as doExportCSV } from '../utils/helpers'

/**
 * Central hook managing all simulation state and actions.
 * Combines state (SimulatorState) and actions (SimulatorActions) into a single return value.
 */
export function useSimulator(): SimulatorState & SimulatorActions {
  /** Number of available memory frames */
  const [frameSize, setFrameSize] = useState(4)
  /** Selected page replacement algorithm */
  const [algorithm, setAlgorithm] = useState<Algorithm>('FIFO')
  /** Comma-separated page reference string input by the user */
  const [inputString, setInputString] = useState('7,0,1,2,0,3,0,4,2,3,0,3,2,1,2,0,1,7,0,1')
  /** Array of simulation steps generated by the last run */
  const [steps, setSteps] = useState<SimulationStep[]>([])
  /** Current position in the simulation timeline */
  const [currentStep, setCurrentStep] = useState(0)
  /** Whether auto-play is active */
  const [isPlaying, setIsPlaying] = useState(false)
  /** Playback speed in milliseconds between steps */
  const [speed, setSpeed] = useState(500)
  /** Whether a simulation has been run at least once */
  const [hasRun, setHasRun] = useState(false)
  /** Index of a fault step currently being visually highlighted */
  const [highlightedFault, setHighlightedFault] = useState<number | null>(null)
  /** Validation error message to display to the user */
  const [error, setError] = useState('')
  /** Ref for the auto-play interval timer */
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null)

  /** Parse input, validate, and run the simulation */
  const runSimulation = useCallback(() => {
    const raw = inputString.split(',').map(s => s.trim()).filter(Boolean)
    if (raw.length === 0) { setError('Please enter a page reference string.'); return }
    if (frameSize < 1) { setError('Frame size must be at least 1.'); return }

    const invalid = raw.filter(s => !/^\d+$/.test(s))
    if (invalid.length > 0) { setError(`Invalid values: ${invalid.join(', ')}. Use comma-separated numbers.`); return }

    setError('')
    const pages = raw.map(Number)
    const result = simulate(pages, frameSize, algorithm)
    setSteps(result)
    setCurrentStep(0)
    setHasRun(true)
    setIsPlaying(false)
    setHighlightedFault(null)
  }, [inputString, frameSize, algorithm])

  /** Reset all state back to pre-run defaults */
  const reset = useCallback(() => {
    setIsPlaying(false)
    setSteps([])
    setCurrentStep(0)
    setHasRun(false)
    setHighlightedFault(null)
    setError('')
  }, [])

  /** Advance one step forward in the simulation */
  const stepForward = useCallback(() => {
    setCurrentStep(prev => {
      const next = Math.min(prev + 1, steps.length)
      if (next > 0 && steps[next - 1]?.isFault) {
        setHighlightedFault(next - 1)
        setTimeout(() => setHighlightedFault(null), 600)
      }
      return next
    })
  }, [steps])

  /** Go back one step in the simulation */
  const stepBackward = useCallback(() => {
    setCurrentStep(prev => Math.max(prev - 1, 0))
  }, [])

  /** Toggle auto-play on/off */
  const togglePlay = useCallback(() => {
    setIsPlaying(p => !p)
  }, [])

  /** Set up interval for auto-play when isPlaying is active */
  useEffect(() => {
    if (isPlaying) {
      intervalRef.current = setInterval(() => {
        setCurrentStep(prev => {
          if (prev >= steps.length) {
            setIsPlaying(false)
            return prev
          }
          if (steps[prev]?.isFault) {
            setHighlightedFault(prev)
            setTimeout(() => setHighlightedFault(null), 600)
          }
          return prev + 1
        })
      }, speed)
    }
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current)
    }
  }, [isPlaying, speed, steps.length])

  /** Export simulation results to a CSV file */
  const exportCSV = useCallback(() => {
    doExportCSV(steps, frameSize, algorithm)
  }, [steps, frameSize, algorithm])

  return {
    frameSize, setFrameSize,
    algorithm, setAlgorithm,
    inputString, setInputString,
    steps,
    currentStep,
    isPlaying,
    speed, setSpeed,
    hasRun,
    highlightedFault,
    error,
    runSimulation,
    reset,
    stepForward,
    stepBackward,
    togglePlay,
    exportCSV,
  }
}
